version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - apt-get update && apt-get upgrade -y
      - pip install pipenv
      - pip install -U pytest
      - pipenv sync --dev
      - pipenv install --dev
  build:
    commands:
      - echo Build started on `date`
      - pipenv run aws_tests
  post_build:
    commands:
      - echo Build completed on `date`